spring:
  application:
  name: hierarchy-jpa-challenge
  datasource:
    url: jdbc:h2:mem:conference
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    ROOT: WARN
    org.springframework.*: WARN
    com.popov.*: DEBUG
